import Foundation

public enum ClipFormatting {
    /// Pasteboard types that apps use to mark content that should not be recorded
    /// (see nspasteboard.org). Password managers set these on copied passwords.
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public static func shouldIgnore(types: [String]) -> Bool {
        types.contains { ignoredTypes.contains($0) }
    }

    /// Single-line menu title: whitespace runs (including newlines) collapse to one space,
    /// and long text is cut with an ellipsis.
    public static func menuTitle(for text: String, maxLength: Int = 60) -> String {
        let collapsed = text
            .split(whereSeparator: { $0.isWhitespace })
            .joined(separator: " ")
        guard collapsed.count > maxLength else { return collapsed }
        return String(collapsed.prefix(maxLength - 1)) + "…"
    }
}
